export const projectContent = {
  cognite: {
    title1: "Enabling Engineers to use Data",
    title2: "Science",
    company: "Cognite",
    location: "Oslo, Norway",
    role: ["Front-End Engineer", "Product Designer"],
    team: [
      "Me",
      "Infrastructure Engineer",
      "Data Scientist 1",
      "Data Scientist 2",
      "Front-End Engineer (50%)",
    ],
    duration: "4 Months",
  },
  microsoft: {
    title1: "Microsoft",
    title2: "Microsoft",
    company: "Microsoft",
    location: "Seattle, US",
    role: [],
    team: [],
    duration: "4 Months",
  },
  bungalow: {
    title1: "Bungalow",
    title2: "Bungalow",
    company: "Bungalow",
    location: "Kitchener, Canada",
    role: [],
    team: [],
    duration: "4 Months",
  },
  cibc: {
    title1: "CIBC",
    title2: "CIBC",
    company: "CIBC",
    location: "Toronto, Canada",
    role: [],
    team: [],
    duration: "4 Months",
  },
};
