export const projectContent = {
  raytracer: {
    title1: "Building a Graphics",
    title2: "Ray Tracer",
    articleType: "PROJECT SHOWCASE",
    company: "University of Waterloo",
    location: "2021",
    team: ["Me"],
    role: ["Designer", "Engineer"],
    duration: "16 weeks",
  },
  crescendio: {
    title1: "Collaborative Music Production",
    title2: "",
    articleType: "PROJECT SHOWCASE",
    company: "University of Waterloo",
    location: "2020",
    role: ["Designer", "Engineer"],
    team: ["5 Members"],
    duration: "16 weeks",
  },
  cognite: {
    title1: "Enabling Engineers to use Data",
    title2: "Science",
    articleType: "CASE STUDY",
    company: "Cognite",
    location: "Oslo, Norway",
    role: ["Front-End Engineer", "Product Designer"],
    team: [
      "Me",
      "Infrastructure Engineer",
      "Data Scientist 1",
      "Data Scientist 2",
      "Front-End Engineer (50%)",
    ],
    duration: "16 weeks",
  },
  microsoft: {
    title1: "Microsoft",
    title2: "Microsoft",
    articleType: "CASE STUDY",
    company: "Microsoft",
    location: "Seattle, US",
    role: [],
    team: [],
    duration: "4 Months",
  },
  bungalow: {
    title1: "Bungalow",
    title2: "Bungalow",
    articleType: "CASE STUDY",
    company: "Bungalow",
    location: "Kitchener, Canada",
    role: [],
    team: [],
    duration: "4 Months",
  },
  cibc: {
    title1: "CIBC",
    title2: "CIBC",
    articleType: "CASE STUDY",
    company: "CIBC",
    location: "Toronto, Canada",
    role: [],
    team: [],
    duration: "4 Months",
  },
};
